import { Input } from "@/components/ui/input"
import ElectionTable from "./electionTable"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Manage Elections",
    description: "Generated by create next app",
};

const ManageCandidatePage = () => {
    return (
        <>
            <main className="w-full min-h-screen flex-col pt-5 px-16">
                {/* <div className=" flex items-center justify-end gap-3"> */}
                    {/* <Button>Add</Button> */}
                {/* </div> */}
                <div className="w-full flex items-center  flex-col">
                    <ElectionTable />
                </div>
            </main>
        </>
    )
}
export default ManageCandidatePage