import { getServerSession } from "next-auth"
import LoginForm from "./loginForm"
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Login",
    description: "Generated by create next app",
};

export default async function LoginVoter() {
    const session = await getServerSession();
    if (session) {
        console.log("Login secssion redirected");
        redirect('/') //redirect after signin, but won't work
    }
    return (
        <>
            <main className="w-full flex items-center min-h-screen flex-col pt-24">
                <LoginForm />
            </main >
        </>
    )
}