import ElectionCard from "@/components/ElectionCard";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Elections",
    description: "Generated by create next app",
  };

export default function Election() {
    return (
        <>
            <main className="w-full flex items-center min-h-screen flex-col pt-24">
                    <ElectionCard />
                    {/* <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard />
                    <ElectionCard /> */}
            </main>
        </>
    )
}