import { getServerSession } from "next-auth"
import RegisterVoterForm from "./registerForm"
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Register",
    description: "Generated by create next app",
  };

const RegisterVoter = async () => {
    const session = await getServerSession();
    // While logged in, if we try to access the 'auth/register' pages, it will redirect to '/'
    if (session) {
        redirect('/');
    }
    return (
        <>
            <main className="w-full flex items-center min-h-screen flex-col pt-16">
                <RegisterVoterForm />
            </main>
        </>
    )
}
export default RegisterVoter






